### ISSUE TITLE
Storybook 6: WithThemeProvider won't receive themes when selecting new component

### ISSUE THREAD

**Issue by TomasHnidek** [elsa-santos/storybook-addon-styled-components-themes#1]
When using new version of storybook, when I click on different component, it will not get drawn out. The issue is that WithThemeProvider wo't receive the themes within the useEffect and will draw the empty ReactFragment.

**Comment by TomasHnidek** [comment]
It is fixed when I select another theme, but that's not very good solution.

**Comment by yuriincentro** [comment]
I have the same problem
